export const itemRarity = ['Common', 'Uncommon', 'Rare', 'Epic', 'Legendary']

export const ringItems = [
  {
    id: 0,
    itemType: 0,
    classType: 0,
    level: 0,
    rate: 100,
    name: 'Gold Ring of Burn Defense',
  },
  {
    id: 1,
    itemType: 0,
    classType: 1,
    level: 0,
    rate: 90,
    name: 'Gold Ring of Avoidance',
  },
  {
    id: 2,
    itemType: 0,
    classType: 2,
    level: 0,
    rate: 80,
    name: 'Steel Ring of Fiendsbane',
  },
  {
    id: 3,
    itemType: 0,
    classType: 3,
    level: 0,
    rate: 70,
    name: 'Titanium Ring of Fey Resistance',
  },
  {
    id: 4,
    itemType: 0,
    classType: 4,
    level: 0,
    rate: 60,
    name: 'Gold Ring of Energy',
  },
  {
    id: 5,
    itemType: 0,
    classType: 0,
    level: 1,
    rate: 60,
    name: 'Titanium Ring of the Forest',
  },
  {
    id: 6,
    itemType: 0,
    classType: 1,
    level: 1,
    rate: 50,
    name: 'Silver Ring of Restoration',
  },
  {
    id: 7,
    itemType: 0,
    classType: 2,
    level: 1,
    rate: 50,
    name: 'Bronze Ring of Alchemy',
  },
  {
    id: 8,
    itemType: 0,
    classType: 3,
    level: 1,
    rate: 50,
    name: 'Platinum Ring of Confusion',
  },
  {
    id: 9,
    itemType: 0,
    classType: 4,
    level: 1,
    rate: 40,
    name: 'Rose Gold Ring of Reaction',
  },
  {
    id: 10,
    itemType: 0,
    classType: 0,
    level: 2,
    rate: 40,
    name: 'Diamond Ring of Spikes',
  },
  {
    id: 11,
    itemType: 0,
    classType: 1,
    level: 2,
    rate: 40,
    name: 'Brass Ring of Advantage',
  },
  {
    id: 12,
    itemType: 0,
    classType: 2,
    level: 2,
    rate: 40,
    name: 'Kyanite Ring of Courage',
  },
  {
    id: 13,
    itemType: 0,
    classType: 3,
    level: 2,
    rate: 30,
    name: 'Gold Ring of Ingenuity',
  },
  {
    id: 14,
    itemType: 0,
    classType: 4,
    level: 2,
    rate: 30,
    name: 'Silver Ring of the Deep Sleep',
  },
  {
    id: 15,
    itemType: 0,
    classType: 0,
    level: 3,
    rate: 30,
    name: 'Gold Ring of Combustion',
  },
  {
    id: 16,
    itemType: 0,
    classType: 1,
    level: 3,
    rate: 30,
    name: 'Silver Ring of Duplication',
  },
  {
    id: 17,
    itemType: 0,
    classType: 2,
    level: 3,
    rate: 20,
    name: 'Brass Ring of Quick Reflexes',
  },
  {
    id: 18,
    itemType: 0,
    classType: 3,
    level: 3,
    rate: 20,
    name: 'Marble Ring of Retention',
  },
  {
    id: 19,
    itemType: 0,
    classType: 4,
    level: 3,
    rate: 20,
    name: 'Pearl Ring of Spirit',
  },
  {
    id: 20,
    itemType: 0,
    classType: 0,
    level: 4,
    rate: 20,
    name: 'Stone Ring of Increase',
  },
  {
    id: 21,
    itemType: 0,
    classType: 1,
    level: 4,
    rate: 10,
    name: 'Steel Ring of Protection',
  },
  {
    id: 22,
    itemType: 0,
    classType: 2,
    level: 4,
    rate: 10,
    name: 'Gold Ring of Determination',
  },
  {
    id: 23,
    itemType: 0,
    classType: 3,
    level: 4,
    rate: 5,
    name: 'Amber Ring of Withstanding',
  },
  {
    id: 24,
    itemType: 0,
    classType: 4,
    level: 4,
    rate: 5,
    name: 'Etheric Ring of Renewal',
  },
]

export const potionItems = [
  {
    id: 0,
    itemType: 1,
    classType: 0,
    level: 0,
    rate: 90,
    name: 'Luck Potion',
  },
  {
    id: 1,
    itemType: 1,
    classType: 0,
    level: 0,
    rate: 80,
    name: 'Levitation Potion',
  },
  {
    id: 2,
    itemType: 1,
    classType: 0,
    level: 0,
    rate: 70,
    name: 'Strong Brew',
  },
  {
    id: 3,
    itemType: 1,
    classType: 0,
    level: 0,
    rate: 70,
    name: 'Pava Root Potion',
  },
  {
    id: 4,
    itemType: 1,
    classType: 0,
    level: 0,
    rate: 70,
    name: 'Spring Water Flask',
  },
  {
    id: 5,
    itemType: 1,
    classType: 0,
    level: 0,
    rate: 60,
    name: 'Mirroring Potion',
  },
  {
    id: 6,
    itemType: 1,
    classType: 0,
    level: 1,
    rate: 60,
    name: 'Phial of Defense',
  },
  {
    id: 7,
    itemType: 1,
    classType: 0,
    level: 1,
    rate: 60,
    name: 'Slime Vial',
  },
  {
    id: 8,
    itemType: 1,
    classType: 0,
    level: 1,
    rate: 50,
    name: 'Ichor Draft',
  },
  {
    id: 9,
    itemType: 1,
    classType: 0,
    level: 1,
    rate: 50,
    name: 'Holy Water',
  },
  {
    id: 10,
    itemType: 1,
    classType: 0,
    level: 1,
    rate: 50,
    name: 'Murky Flask',
  },
  {
    id: 11,
    itemType: 1,
    classType: 0,
    level: 2,
    rate: 40,
    name: 'Arcane Brew',
  },
  {
    id: 12,
    itemType: 1,
    classType: 0,
    level: 2,
    rate: 40,
    name: 'Berserkers Brew',
  },
  {
    id: 13,
    itemType: 1,
    classType: 0,
    level: 2,
    rate: 40,
    name: 'Spirit Vial',
  },
  {
    id: 14,
    itemType: 1,
    classType: 0,
    level: 2,
    rate: 30,
    name: 'Flask of Resolve',
  },
  {
    id: 15,
    itemType: 1,
    classType: 0,
    level: 2,
    rate: 30,
    name: 'Lucidity Elixir',
  },
  {
    id: 16,
    itemType: 1,
    classType: 0,
    level: 3,
    rate: 20,
    name: 'Philter of Redemption',
  },
  {
    id: 17,
    itemType: 1,
    classType: 0,
    level: 3,
    rate: 20,
    name: 'Lavender Extract',
  },
  {
    id: 18,
    itemType: 1,
    classType: 0,
    level: 3,
    rate: 20,
    name: 'Trippie Draught',
  },
  {
    id: 19,
    itemType: 1,
    classType: 0,
    level: 3,
    rate: 10,
    name: 'Phantom Phial',
  },
  {
    id: 20,
    itemType: 1,
    classType: 0,
    level: 3,
    rate: 10,
    name: 'Bloodlust Flask',
  },
  {
    id: 21,
    itemType: 1,
    classType: 0,
    level: 4,
    rate: 10,
    name: 'Misty Phial',
  },
  {
    id: 22,
    itemType: 1,
    classType: 0,
    level: 4,
    rate: 10,
    name: 'Spirit Elixir',
  },
  {
    id: 23,
    itemType: 1,
    classType: 0,
    level: 4,
    rate: 5,
    name: 'Dew Drop Vial',
  },
  {
    id: 24,
    itemType: 1,
    classType: 0,
    level: 4,
    rate: 5,
    name: 'Master Brew',
  },
]

export const trinketItems = [
  {
    id: 0,
    itemType: 2,
    classType: 0,
    level: 0,
    rate: 80,
    name: 'Wee Red Mushroom',
  },
  {
    id: 1,
    itemType: 2,
    classType: 0,
    level: 0,
    rate: 80,
    name: 'Pine Resin',
  },
  {
    id: 2,
    itemType: 2,
    classType: 0,
    level: 0,
    rate: 80,
    name: 'Birdcage',
  },
  {
    id: 3,
    itemType: 2,
    classType: 0,
    level: 0,
    rate: 70,
    name: 'Glowing Rune',
  },
  {
    id: 4,
    itemType: 2,
    classType: 0,
    level: 0,
    rate: 70,
    name: 'Ether Crystal',
  },
  {
    id: 5,
    itemType: 2,
    classType: 0,
    level: 0,
    rate: 60,
    name: 'Rabbit Foot',
  },
  {
    id: 6,
    itemType: 2,
    classType: 0,
    level: 0,
    rate: 60,
    name: 'Poisonous Frog',
  },
  {
    id: 7,
    itemType: 2,
    classType: 0,
    level: 1,
    rate: 50,
    name: 'Acorns',
  },
  {
    id: 8,
    itemType: 2,
    classType: 0,
    level: 1,
    rate: 50,
    name: 'Torch',
  },
  {
    id: 9,
    itemType: 2,
    classType: 0,
    level: 1,
    rate: 50,
    name: 'Dream Amulet',
  },
  {
    id: 10,
    itemType: 2,
    classType: 0,
    level: 1,
    rate: 40,
    name: 'Dusty Scroll',
  },
  {
    id: 11,
    itemType: 2,
    classType: 0,
    level: 1,
    rate: 40,
    name: 'Crustacean Claw',
  },
  {
    id: 12,
    itemType: 2,
    classType: 0,
    level: 1,
    rate: 40,
    name: 'Goblet',
  },
  {
    id: 13,
    itemType: 2,
    classType: 0,
    level: 1,
    rate: 40,
    name: 'Draca Fangs',
  },
  {
    id: 14,
    itemType: 2,
    classType: 0,
    level: 2,
    rate: 30,
    name: 'Gargoyle',
  },
  {
    id: 15,
    itemType: 2,
    classType: 0,
    level: 2,
    rate: 30,
    name: 'Bat Wing',
  },
  {
    id: 16,
    itemType: 2,
    classType: 0,
    level: 2,
    rate: 30,
    name: 'Runic Tome',
  },
  {
    id: 17,
    itemType: 2,
    classType: 0,
    level: 2,
    rate: 20,
    name: 'Lucky Die',
  },
  {
    id: 18,
    itemType: 2,
    classType: 0,
    level: 2,
    rate: 20,
    name: 'Golem Eye',
  },
  {
    id: 19,
    itemType: 2,
    classType: 0,
    level: 3,
    rate: 10,
    name: 'Phoenix Egg',
  },
  {
    id: 20,
    itemType: 2,
    classType: 0,
    level: 3,
    rate: 10,
    name: 'Abyssal Talisman',
  },
  {
    id: 21,
    itemType: 2,
    classType: 0,
    level: 3,
    rate: 10,
    name: 'Enchanted Goggles',
  },
  {
    id: 22,
    itemType: 2,
    classType: 0,
    level: 3,
    rate: 10,
    name: 'Magic Coinpurse',
  },
  {
    id: 23,
    itemType: 2,
    classType: 0,
    level: 4,
    rate: 5,
    name: 'Hand Candle',
  },
  {
    id: 24,
    itemType: 2,
    classType: 0,
    level: 4,
    rate: 5,
    name: 'Mask of Valathor',
  },
  {
    id: 25,
    itemType: 2,
    classType: 0,
    level: 4,
    rate: 5,
    name: 'Wild Cucumber',
  },
  {
    id: 26,
    itemType: 2,
    classType: 0,
    level: 4,
    rate: 5,
    name: 'Underdark Egg',
  },
]
